ignored:
    - DL3008 # https://github.com/hadolint/hadolint/wiki/DL3008
    - DL3018 # https://github.com/hadolint/hadolint/wiki/DL3018
    - DL3022 # https://github.com/hadolint/hadolint/wiki/DL3022
