version: '3.9'

services:

    blackfire:
        build:
            context: docker/blackfire
            dockerfile: Dockerfile
        env_file:
            - docker/blackfire/.env
        ports:
            - '127.0.0.1:8707:8707'

networks:
    default:
        external: true
        name: ${DOCKER_NETWORK_NAME:-boxuk-docker}
