name: Deploy to Git
description: 'Deploy to a Git Repository'
inputs:
  DEPLOY_KEY:
    description: 'SSH Key'
    required: true
  GIT_URL:
    description: 'Git URL to deploy to (eg: git@github.com:wpcomvip/boxuk or git@git.wpengine.com/boxuk.git)'
    required: true
  BRANCH:
    description: 'Branch to Deploy to (main, master, develop, preprod)'
    required: true
  SOURCE_DIR:
    description: 'Source Directory relative to the root of the repository to deploy from (e.g. ./wp-content)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Deploy Key
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.DEPLOY_KEY }}" > ~/.ssh/DEPLOY_KEY
        sudo chmod 600 ~/.ssh/DEPLOY_KEY

    - name: Clone Remote Repo to temp-deploy directory
      shell: bash
      env:
        GIT_SSH_COMMAND: ssh -i ~/.ssh/DEPLOY_KEY
      run: git clone ${{ inputs.GIT_URL }} --branch ${{ inputs.BRANCH }} --depth=1 temp-deploy

    - name: Copy Changes to temp-deploy directory
      shell: bash
      run: rsync --recursive --delete --exclude='.git' --exclude-from='.deployignore' ${{ inputs.SOURCE_DIR }} ./temp-deploy/

    - name: Commit Changes
      shell: bash
      env:
        GIT_SSH_COMMAND: ssh -i ~/.ssh/DEPLOY_KEY
      run: |
        cd temp-deploy
        git config user.name "Box UK Automated Deployment"
        git config user.email "deployments@boxuk.com"
        git add .
        git commit -m "[DEPLOYMENT] Automated deployment from Box UK ${{ inputs.BRANCH }} to VIP ${{ inputs.BRANCH }}"
        git push origin ${{ inputs.BRANCH }}

    - name: Cleanup
      shell: bash
      run: rm -rf temp-deploy
