services:
    _defaults:
        autowire: true
        autoconfigure: true

    BoxUk\Mu\Plugins\Sample\SampleClass:
        public: true # If a service is being used directly (i.e. not being injected into another class) you have to mark it as public.
