services:
    _defaults:
        autowire: true
        autoconfigure: true

    BoxUk\Mu\Plugins\SampleWithTaggedHooks\SampleWithTaggedHooksClass:
        public: true

    BoxUk\Mu\Plugins\SampleWithTaggedHooks\HookListener:
        tags:
            - { name: 'wp_hook', action: 'init' } # Will call the on_init method on HookListener
            - { name: 'wp_hook', filter: 'the_content' } # Will call the on_the_content method on HookListener
            - { name: 'wp_hook', action: 'plugins_loaded', method: 'plugins_have_now_loaded' } # Will call the plugins_have_now_loaded method on HookListener
