name: "Lint"

on:
    pull_request:
        paths:
            - "docker/**/Dockerfile"
            - "docker/app/Dockerfile_xdebug"
    push:
        branches:
            - main

env:
    fail-fast: true

jobs:
    lint-docker:
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout"
              uses: actions/checkout@v2

            - name: "Lint Dockerfile(s)"
              uses: jbergstroem/hadolint-gh-action@v1
              with:
                dockerfile: "./docker/**/Dockerfile ./docker/app/Dockerfile_xdebug"
